export const browserCoreExamples = [
  "blockclaw browser status",
  "blockclaw browser start",
  "blockclaw browser stop",
  "blockclaw browser tabs",
  "blockclaw browser open https://example.com",
  "blockclaw browser focus abcd1234",
  "blockclaw browser close abcd1234",
  "blockclaw browser screenshot",
  "blockclaw browser screenshot --full-page",
  "blockclaw browser screenshot --ref 12",
  "blockclaw browser snapshot",
  "blockclaw browser snapshot --format aria --limit 200",
  "blockclaw browser snapshot --efficient",
  "blockclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "blockclaw browser navigate https://example.com",
  "blockclaw browser resize 1280 720",
  "blockclaw browser click 12 --double",
  'blockclaw browser type 23 "hello" --submit',
  "blockclaw browser press Enter",
  "blockclaw browser hover 44",
  "blockclaw browser drag 10 11",
  "blockclaw browser select 9 OptionA OptionB",
  "blockclaw browser upload /tmp/blockclaw/uploads/file.pdf",
  'blockclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "blockclaw browser dialog --accept",
  'blockclaw browser wait --text "Done"',
  "blockclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "blockclaw browser console --level error",
  "blockclaw browser pdf",
];
